package com.griffith.imageguessergame



// Function to get images based on category and shuffle them
fun getImagesForCategory(categoryName: String): List<Pair<Int, String>> {
    // Define images for each category
    val animalImages = listOf(
        R.drawable.animal_aardvark to "Aardvark",
        R.drawable.animal_alligator to "Alligator",
        R.drawable.animal_anaconda to "Anaconda",
        R.drawable.animal_axolotl to "Axolotl",
        R.drawable.animal_bear to "Bear",
        R.drawable.animal_beetle to "Beetle",
        R.drawable.animal_bison to "Bison",
        R.drawable.animal_blueshark to "Blueshark",
        R.drawable.animal_butterfly to "Butterfly",
        R.drawable.animal_camel to "Camel",
        R.drawable.animal_chameleon to "Chameleon",
        R.drawable.animal_chipmunk to "Chipmunk",
        R.drawable.animal_cobra to "Cobra",
        R.drawable.animal_crocodile to "Crocodile",
        R.drawable.animal_crow to "Crow",
        R.drawable.animal_dolphin to "Dolphin",
        R.drawable.animal_duck to "Duck",
        R.drawable.animal_eagle to "Eagle",
        R.drawable.animal_elephant to "Elephant",
        R.drawable.animal_falcon to "Falcon",
        R.drawable.animal_flamingo to "Flamingo",
        R.drawable.animal_fox to "Fox",
        R.drawable.animal_frog to "Frog",
        R.drawable.animal_gecko to "Gecko",
        R.drawable.animal_giraffe to "Giraffe",
        R.drawable.animal_goose to "Goose",
        R.drawable.animal_jellyfish to "Jellyfish",
        R.drawable.animal_kangaroo to "Kangaroo",
        R.drawable.animal_komododragon to "Komododragon",
        R.drawable.animal_leatherbackturtle to "Leatherback Turtle",
        R.drawable.animal_leopard to "Leopard",
        R.drawable.animal_lion to "Lion",
        R.drawable.animal_monkey to "Monkey",
        R.drawable.animal_moose to "Moose",
        R.drawable.animal_octopus to "Octopus",
        R.drawable.animal_ostrich to "Ostrich",
        R.drawable.animal_owl to "Owl",
        R.drawable.animal_panda to "Panda",
        R.drawable.animal_peacock to "Peacock",
        R.drawable.animal_penguin to "Penguin",
        R.drawable.animal_prayingmantis to "Praying Mantis",
        R.drawable.animal_pufferfish to "Pufferfish",
        R.drawable.animal_rhino to "Rhino",
        R.drawable.animal_salamander to "Salamander",
        R.drawable.animal_scorpion to "Scorpion",
        R.drawable.animal_seahorse to "Seahorse",
        R.drawable.animal_seaturtle to "Sea turtle",
        R.drawable.animal_spider to "Spider",
        R.drawable.animal_squid to "Squid",
        R.drawable.animal_stingray to "Sting ray",
        R.drawable.animal_swan to "Swan",
        R.drawable.animal_tortoise to "Tortoise",
        R.drawable.animal_whale to "Whale",
        R.drawable.animal_woodpecker to "Woodpecker"
    )

    val logoImages = listOf(
        R.drawable.logo_apple to "Apple",
        R.drawable.logo_adidas to "Adidas",
        R.drawable.logo_amazon to "Amazon",
        R.drawable.logo_audi to "Audi",
        R.drawable.logo_batman to "Batman",
        R.drawable.logo_bbc to "BBC",
        R.drawable.logo_bmw to "BMW",
        R.drawable.logo_bp to "BP",
        R.drawable.logo_chanel to "Chanel",
        R.drawable.logo_cocacola to "Coca Cola",
        R.drawable.logo_Colgate to "Colgate",
        R.drawable.logo_continental to "Continental",
        R.drawable.logo_dell to "Dell",
        R.drawable.logo_disney to "Disney",
        R.drawable.logo_dove to "Dove",
        R.drawable.logo_ebay to "Ebay",
        R.drawable.logo_exxonmobil to "Exxonmobil",
        R.drawable.logo_facebook to "Facebook",
        R.drawable.logo_fedex to "Fedex",
        R.drawable.logo_ford to "Ford",
        R.drawable.logo_gap to "Gap",
        R.drawable.logo_google to "Google",
        R.drawable.logo_honda to "Honda",
        R.drawable.logo_hp to "HP",
        R.drawable.logo_hyundai to "Hyundai",
        R.drawable.logo_ibm to "IBM",
        R.drawable.logo_lacoste to "Lactose",
        R.drawable.logo_mastercard to "MasterCard",
        R.drawable.logo_mcdonald to "McDonald",
        R.drawable.logo_mercedes to "Mercedes",
        R.drawable.logo_microsoft to "Microsoft",
        R.drawable.logo_mitsubishi to "Mitsubishi",
        R.drawable.logo_nationalgeographic to "National Geographic",
        R.drawable.logo_nestle to "Nestle",
        R.drawable.logo_nike to "Nike",
        R.drawable.logo_olympics to "Olympics",
        R.drawable.logo_paypal to "PayPal",
        R.drawable.logo_pepsi to "Pepsi",
        R.drawable.logo_ps to "Play station",
        R.drawable.logo_rolex to "Rolex",
        R.drawable.logo_samsung to "Samsung",
        R.drawable.logo_shell to "Shell",
        R.drawable.logo_sony to "Sony",
        R.drawable.logo_starbucks to "Starbucks",
        R.drawable.logo_superman to "Superman",
        R.drawable.logo_target to "Target",
        R.drawable.logo_toyota to "Toyota",
        R.drawable.logo_unilever to "Unilever",
        R.drawable.logo_Verizon to "Verizon",
        R.drawable.logo_visa to "Visa",
        R.drawable.logo_volkswagen to "Volkswagen",
        R.drawable.logo_walmart to "Walmart",
        R.drawable.logo_worldwidefund to "World Wide Fund",
    )

    val fruitImages = listOf(
        R.drawable.fruit_africancherry to "African Cherry",
        R.drawable.fruit_apple to "Apple",
        R.drawable.fruit_apricots to "Apricots",
        R.drawable.fruit_aubergines to "Aubergine",
        R.drawable.fruit_avocados to "Avocados",
        R.drawable.fruit_bananas to "Banana",
        R.drawable.fruit_blackberies to "Blackberry",
        R.drawable.fruit_butternutsquash to "Butternut Squash",
        R.drawable.fruit_cantaloupe to "Cantaloupe",
        R.drawable.fruit_cashew to "Cashew",
        R.drawable.fruit_cherries to "Cherries",
        R.drawable.fruit_clementines to "Clementines",
        R.drawable.fruit_coconut to "Coconuts",
        R.drawable.fruit_dates to "Dates",
        R.drawable.fruit_dragonfruit to "Dragon Fruit",
        R.drawable.fruit_elderberries to "Elderberry",
        R.drawable.fruit_figs to "Figs",
        R.drawable.fruit_fingerlime to "Finger Lime",
        R.drawable.fruit_grapefruit to "Grape Fruit",
        R.drawable.fruit_grapes to "Grapes",
        R.drawable.fruit_guava to "Guava",
        R.drawable.fruit_honeydewmelons to "Honeydew Melons",
        R.drawable.fruit_jackfruit to "Jack fruit",
        R.drawable.fruit_kiwis to "Kiwi",
        R.drawable.fruit_lemons to "Lemon",
        R.drawable.fruit_mango to "Mango",
        R.drawable.fruit_nectarines to "Nectarine",
        R.drawable.fruit_olives to "Olive",
        R.drawable.fruit_oranges to "Orange",
        R.drawable.fruit_papaya to "Papaya",
        R.drawable.fruit_pawpaw to "pawpaw",
        R.drawable.fruit_peach to "Peach",
        R.drawable.fruit_pears to "Pears",
        R.drawable.fruit_peppers to "Peppers",
        R.drawable.fruit_pineapples to "Pineapple",
        R.drawable.fruit_pumpkins to "Pumpkins",
        R.drawable.fruit_quince to "Quince",
        R.drawable.fruit_raisins to "Raisins",
        R.drawable.fruit_raspberry to "Raspberry",
        R.drawable.fruit_satsumas to "Satsumas",
        R.drawable.fruit_soursop to "Soursop",
        R.drawable.fruit_strawberries to "Strawberry",
        R.drawable.fruit_tomatoes to "Tomato",
        R.drawable.fruit_ugli to "Ugli",
        R.drawable.fruit_watermelons to "Watermelon",
        R.drawable.fruit_zucchini to "Zucchini",
    )

    // Combine all images for the random category
    val allImages = animalImages + logoImages + fruitImages

    return when (categoryName) {
        "Animals" -> animalImages.shuffled()
        "Logos" -> logoImages.shuffled()
        "Fruits" -> fruitImages.shuffled()
        "Random" -> allImages.shuffled() // Random compilation of all images
        else -> emptyList()
    }
}
